#!/usr/bin/env python
# -*- coding: utf8 -*-

import logging
logging.basicConfig(level=logging.DEBUG)

from bootstrap import bootstrap, ve

import os
bootstrap(os.path.dirname(os.path.abspath(__file__)))

ve('command -v python')
